[package]
name = "keccak-p-x"
version = "0.1.0"
authors = ["Mineco1006"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "*"
keccak-p = "*"

[[bench]]
name = "keccak-benches"
harness = false